Set up sentry on application
bolom/gilbertmarcel pull request #33
Opened 2023-07-22 10:44 UTC by EEUAAAIA

Sentry initialization with "gem sentry-ruby" and file sentry.rb. 
On this file adding code to have only productions' errors : using condition if (if Rails.env.production?) to initialize Sentry only if we are in production.

2023-07-22 14:43 UTC, bolom requested changes

2023-07-22 14:43 UTC, bolom commented on Gemfile
> +gem "sentry-ruby"
missing sentry-rails

2023-07-22 14:43 UTC, bolom commented on config/initializers/sentry.rb
> +    config.dsn = 'https://19fa4de0dc2c4c519e524dbf9b29ff45@o221731.ingest.sentry.io/4505572519772160'
don't harcode dsn use Rails.crendentials instead of.

`config.dsn = Rails.application.credentials[Rails.env.to_sym][:sentry][:dsn]`

I will set the value in the master.key

2023-07-22 14:43 UTC, bolom commented on config/initializers/sentry.rb
> +if Rails.env.production?
Don't need to add a condition. The DSN will be set only for production

2023-07-22 23:41 UTC, EEUAAAIA commented on Gemfile
> +gem "sentry-ruby"
Done

2023-07-22 23:56 UTC, EEUAAAIA commented on config/initializers/sentry.rb
> +if Rails.env.production?
Done

2023-07-23 05:40 UTC, bolom approved these changes

2023-07-23 05:52 UTC, merged