Add localization for hardcoded text strings
bolom/gilbertmarcel pull request #44
Opened 2023-07-27 14:21 UTC by EEUAAAIA

I searched all the lines of harcoded code and I defined keys in the fr.yml file then I used the t() method to translate these keys into the corresponding views.

2023-07-28 07:16 UTC, bolom commented on app/views/default/pages/homepage.html.erb
> +        <%= t('my_journal')%>
Be careful and ensure to check if it doesn't break the design.

2023-07-28 07:18 UTC, bolom requested changes

2023-07-28 07:18 UTC, bolom commented on app/views/default/pages/journal_items.html.erb
> +        <h1><%= t('my_journal') %></h1>
No, here the data is from the variable current_page. The value is not hardcoded.

2023-07-29 23:28 UTC, EEUAAAIA commented on app/views/default/pages/homepage.html.erb
> +        <%= t('my_journal')%>
I had nothing on my locale but it's done

2023-07-29 23:28 UTC, EEUAAAIA commented on app/views/default/pages/journal_items.html.erb
> +        <h1><%= t('my_journal') %></h1>
Done

2023-07-29 23:32 UTC, EEUAAAIA commented on app/views/default/pages/homepage.html.erb
> +        <%= t('my_journal')%>
https://github.com/bolom/gilbertmarcel/blob/d053d178f746cf4292ec7fb44fbfac8843eee021/app/views/default/pages/homepage.html.erb#L108C7-L111C12

2023-07-30 08:01 UTC, merged